
### GENERATED BY ROBBYRUSSELL
. /Users/catmcloughlin/.npm-global/lib/node_modules/robbyrussell/adapters/adapter.bash
### GENERATED BY ROBBYRUSSELL

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
